package com.assignment2.hrmps.model;

import java.io.Serializable;
import java.time.LocalDate;

public class Employee implements Serializable {

    private static final long serialVersionUID = 1L; //Making sure this is serializable so we can write

    private String id; //A couple of properties
    private String firstName;
    private String lastName;
    private Department department;
    private EmploymentType employmentType;
    private double hourlyRate;
    private double monthlySalary;
    private LocalDate hireDate;
    private boolean active = true; //default value of true

    public Employee() {
    }

    public Employee(String id, String firstName, String lastName) { //Auto generated by intellij
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
    }

    //Generating getters and setters with intellij


    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Department getDepartment() {
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    public EmploymentType getEmploymentType() {
        return employmentType;
    }

    public void setEmploymentType(EmploymentType employmentType) {
        this.employmentType = employmentType;
    }

    public double getHourlyRate() {
        return hourlyRate;
    }

    public void setHourlyRate(double hourlyRate) {
        this.hourlyRate = hourlyRate;
    }

    public double getMonthlySalary() {
        return monthlySalary;
    }

    public void setMonthlySalary(double monthlySalary) {
        this.monthlySalary = monthlySalary;
    }

    public LocalDate getHireDate() {
        return hireDate;
    }

    public void setHireDate(LocalDate hireDate) {
        this.hireDate = hireDate;
    }

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    @Override
    public String toString() { //Override to string for the sake of boxes where employees are listed
        return id + " - " + firstName + " " + lastName;
    }
}
